"""add delivery location to user preferences

Revision ID: 0882aeb1000a
Revises: 444fc964dee8
Create Date: 2026-09-18 01:44:45.147375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0882aeb1000a'
down_revision: Union[str, Sequence[str], None] = '444fc964dee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_column('delivery_location')

    # ### end Alembic commands ###
